-dontwarn kotlinx.parcelize.Parcelize
-keep public class com.zohodeskportalsalesiq.RNZDPoratalSalesIQModule {*;}
-keep public class com.zohodeskportalsalesiq.RNZDPortalSalesIQPackage {*;}
-keep class com.zohodeskportalsalesiq.RNZDPoratalSalesIQModule$setCallbackOnInit$1$initCallback$1 {*;}